/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KIconCome: typeof import('~icons/icon/come')['default']
    KIconCome_0: typeof import('~icons/icon/come_0')['default']
    KIconGift: typeof import('~icons/icon/gift')['default']
    KIconGift_0: typeof import('~icons/icon/gift_0')['default']
    KIconHome: typeof import('~icons/icon/home')['default']
    KIconHome_0: typeof import('~icons/icon/home_0')['default']
    KIconMy: typeof import('~icons/icon/my')['default']
    KIconMy_0: typeof import('~icons/icon/my_0')['default']
    KIconUser: typeof import('~icons/icon/user')['default']
    KIconUser_0: typeof import('~icons/icon/user_0')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
